import { ChordQuality, type ChordQualityConfig } from "./types";

export const defaultChordQualities: ChordQualityConfig = {
  root: {
    0: ChordQuality.Major,
    1: ChordQuality.Major,
    2: ChordQuality.Minor,
    3: ChordQuality.Major,
    4: ChordQuality.Minor,
    5: ChordQuality.Major,
    6: ChordQuality.Diminished7,
    7: ChordQuality.Major,
    8: ChordQuality.Major,
    9: ChordQuality.Minor,
    10: ChordQuality.Major,
    11: ChordQuality.HalfDiminished7,
  },
  first: {
    0: ChordQuality.Minor,
    1: ChordQuality.Major,
    2: ChordQuality.Major,
    3: ChordQuality.Minor,
    4: ChordQuality.Major,
    5: ChordQuality.Minor,
    6: ChordQuality.Major,
    7: ChordQuality.Minor,
    8: ChordQuality.Minor,
    9: ChordQuality.Major,
    10: ChordQuality.Minor,
    11: ChordQuality.Major,
  },
  second: {
    0: ChordQuality.Major,
    1: ChordQuality.Major,
    2: ChordQuality.Major,
    3: ChordQuality.Major,
    4: ChordQuality.Minor,
    5: ChordQuality.Major,
    6: ChordQuality.Major,
    7: ChordQuality.Major,
    8: ChordQuality.Major,
    9: ChordQuality.Minor,
    10: ChordQuality.Major,
    11: ChordQuality.Minor,
  },
  third: {
    0: ChordQuality.Minor7,
    1: ChordQuality.Major7,
    2: ChordQuality.Minor7,
    3: ChordQuality.Major7,
    4: ChordQuality.Major7,
    5: ChordQuality.Dominant7,
    6: ChordQuality.Major7,
    7: ChordQuality.Minor7,
    8: ChordQuality.Major7,
    9: ChordQuality.Minor7,
    10: ChordQuality.Dominant7,
    11: ChordQuality.Major7,
  },
};
